name: biher_noticeboard
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0-nullsafety.11
  flutter_svg: ^0.21.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  introduction_screen: ^2.0.0
  provider: ^5.0.0
  salomon_bottom_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    # into
    - assets/into/events.svg
    - assets/into/updates.svg
    - assets/into/notetaking.svg
    - assets/into/notification.svg

    # notes
    - assets/notes/addnotes.svg
    - assets/notes/notesicon.svg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
